### ISSUE TITLE
As a user, I should be able to check  a leaderboard that shows how many events I have been to compared to my friends

### ISSUE THREAD

**Issue by jamiemctaggart** [ejasaityte/sustainable-dev-app#29]
### Todo
- [x] Modify database to add check in counter
- [x] Add check in button to map events 
- [x] Add check in button to single events page
- [x] create leaderboard
- [x] go through the code to check if everything's compatible with the updated users table
