### ISSUE TITLE
As an event organiser, I want  to curate ‘tours’ of sustainable venues that are close together so that more places could be visited.

### ISSUE THREAD

**Issue by LauraNaslenaite** [ejasaityte/sustainable-dev-app#31]
### TASKS

- [ ] Implement direction mapping
- [x] Add 'event organiser' users
- [ ] Allow to select events to add to tour
- [x] Create tour database table
