### ISSUE TITLE
As a user, I should see the address of all events selected on the map

### ISSUE THREAD

**Issue by jamiemctaggart** [ejasaityte/sustainable-dev-app#43]
### Tasks
- [x] Update database format
- [x] Insert new data into database
- [x] Add new data to map page
