### ISSUE TITLE
As a User, I should be able to add friends who are registered on the website

### ISSUE THREAD

**Issue by jamiemctaggart** [ejasaityte/sustainable-dev-app#46]
### Todo
- [x] Add page to register new users
- [x] Modify database to include friends
- [x] Add page to add friends on website
- [x] Implement notification feature for friend requests
- [x] Check if relationship already exists
- [x] Show friends on list
